# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

version: 2.0.{build}

skip_tags: false

skip_non_tags: false

skip_commits:
  message: /Created.*\.(png|jpg|jpeg|bmp|gif)/      # Regex for matching commit message

max_jobs: 1

image: Visual Studio 2017

init:
  - git config --global core.autocrlf input

clone_folder: c:\projects\pact-php

install:
  - cinst php --version 7.1.11
  - cmd: C:\tools\php71\php.exe -i
  - cmd: copy /Y .\test\php.ini C:\tools\php71\
  - appveyor DownloadFile https://getcomposer.org/composer.phar
  - cmd: C:\tools\php71\php.exe .\composer.phar update --ignore-platform-reqs

build: off

test_script:
  - cmd: C:\tools\php71\php.exe .\vendor\phpunit\phpunit\phpunit -c .\phpunit-all-tests.xml
  - appveyor DownloadFile http://cs.sensiolabs.org/download/php-cs-fixer-v2.phar
  - cmd: C:\tools\php71\php.exe php-cs-fixer-v2.phar fix  -v --dry-run --stop-on-violation --using-cache=no --rules=-line_ending .

on_success:
  - echo Success

on_failure:
  - echo Failure

notifications:

# Email
#  - provider: Email
#    to:
#      - user1@email.com
#      - user2@email.com
#    subject: 'Build {{status}}'                  # optional
#    message: "{{message}}, {{commitId}}, ..."    # optional
#    on_build_status_changed: true

